CREATE TABLE MOBILE_DEVICE(
ID BIGINT  PRIMARY KEY AUTO_INCREMENT,
BRAND VARCHAR(255) NOT NULL,
MODEL VARCHAR(255) NOT NULL,
OS VARCHAR(255) NOT NULL,
OS_VERSION VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX "PK_MOBILE_DEVICE" ON "MOBILE_DEVICE"
("BRAND", "MODEL", "OS_VERSION");