CREATE TABLE MOBILE_DEVICE(
ID BIGINT  PRIMARY KEY AUTO_INCREMENT,
BRAND VARCHAR(255) NOT NULL,
MODEL VARCHAR(255) NOT NULL,
OS INT NOT NULL,
OS_VERSION VARCHAR(255) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (BRAND, MODEL, OS_VERSION)
);
